### ISSUE TITLE
Create and Endpoint for an Issue

### ISSUE THREAD

**Issue by jeremyzilar** [brooklynrail/brooklynrail-system#9]
Would it be possible to create a json endpoint that contains all of the articles for a given issue, along with all the meta-data for each article?

**See the article data: https://github.com/brooklynrail/brooklynrail-system/wiki/Data:-Article**

### Issue Endpoint
It would be awesome if this could contain:

https://brooklynrail.org/2018/03/json

- Headline
- Description
- Featured image
- URL
- Author
- Date
- Category

---

### Article Endpoint

https://brooklynrail.org/2018/03/art/LOLA-FLASH-with-Amy-Deneson/json

- Headline
- Description
- Featured image
- URL
- Author
- Date
- Category
- Content ! 
- images rendered as HTML in body

```
<div class="article-image">
  <img src="/article_image/image/21362/ZoeLeonard.jpg">
</div>
```

**Comment by dmgig** [comment]
Hi Jeremy,

These are working. There's probably more data than you need, but better more than less.

Here's some examples: 

*issue* [https://brooklynrail.org/json/2018/06](https://brooklynrail.org/json/2018/06)
*article* [https://brooklynrail.org/json/2018/06/art/FELIX-BERNSTEIN-and-GABE-RUBIN-with-Nick-Bennett](https://brooklynrail.org/json/2018/06/art/FELIX-BERNSTEIN-and-GABE-RUBIN-with-Nick-Bennett)

But it should work on any issue or article.

Here is a little script to show it works. If you just make an html file on your desktop and run it in a browser, you'll see the json show up as a string from the Rail site.

```html
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script>

function executeCall(json){
  $('#display').html(JSON.stringify(json));
}

$.ajax({
  url: "https://brooklynrail.org/json/2018/06/",
  dataType: "jsonp"
});

</script>
<div id="display"></div>
```

Like so.

<img width="669" alt="screenshot 2018-06-27 at 19 45 57" src="https://user-images.githubusercontent.com/9688418/42005491-c388fd0a-7a42-11e8-9527-0fe69252078f.PNG">

This is all on the main site so have at it. Sorry it took a couple of days.

Enjoy your trip!!!
